-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 14:21:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema immoOphelieBolle
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `immoOphelieBolle` ;

-- -----------------------------------------------------
-- Schema immoOphelieBolle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `immoOphelieBolle` DEFAULT CHARACTER SET utf8 ;
USE `immoOphelieBolle` ;

-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`TypeUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`TypeUsers` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`TypeUsers` (
  `idTypeUsers` INT NOT NULL AUTO_INCREMENT,
  `userType` VARCHAR(45) NULL,
  PRIMARY KEY (`idTypeUsers`),
  UNIQUE INDEX `idTypeUsers_UNIQUE` (`idTypeUsers` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`Company` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NULL,
  `siret` INT NULL,
  PRIMARY KEY (`idCompany`),
  UNIQUE INDEX `idCompany_UNIQUE` (`idCompany` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`Agences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`Agences` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`Agences` (
  `idAgences` INT NOT NULL AUTO_INCREMENT,
  `agenceName` VARCHAR(45) NULL,
  PRIMARY KEY (`idAgences`),
  UNIQUE INDEX `idAgences_UNIQUE` (`idAgences` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`RDV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`RDV` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`RDV` (
  `idRDV` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `motif` VARCHAR(45) NULL,
  `Agences_idAgences` INT NOT NULL,
  PRIMARY KEY (`idRDV`, `Agences_idAgences`),
  UNIQUE INDEX `idRDV_UNIQUE` (`idRDV` ASC),
  INDEX `fk_RDV_Agences1_idx` (`Agences_idAgences` ASC),
  CONSTRAINT `fk_RDV_Agences1`
    FOREIGN KEY (`Agences_idAgences`)
    REFERENCES `immoOphelieBolle`.`Agences` (`idAgences`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`Factures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`Factures` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`Factures` (
  `idFactures` INT NOT NULL AUTO_INCREMENT,
  `bankName` VARCHAR(45) NULL,
  `rib` VARCHAR(45) NULL,
  `tva` INT NULL,
  `montantHT` INT NULL,
  `montantTTC` INT NULL,
  PRIMARY KEY (`idFactures`),
  UNIQUE INDEX `idFactures_UNIQUE` (`idFactures` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`ZipCodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`ZipCodes` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`ZipCodes` (
  `idZipCodes` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zipCode` VARCHAR(45) NULL,
  PRIMARY KEY (`idZipCodes`),
  UNIQUE INDEX `idZipCodes_UNIQUE` (`idZipCodes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`Address` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `streetNb` INT NULL,
  `streetComplement` VARCHAR(45) NULL,
  `StreetName` VARCHAR(45) NULL,
  `streetComplementName` VARCHAR(45) NULL,
  `ZipCodes_idZipCodes` INT NOT NULL,
  PRIMARY KEY (`idAddress`, `ZipCodes_idZipCodes`),
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC),
  INDEX `fk_Address_ZipCodes1_idx` (`ZipCodes_idZipCodes` ASC),
  CONSTRAINT `fk_Address_ZipCodes1`
    FOREIGN KEY (`ZipCodes_idZipCodes`)
    REFERENCES `immoOphelieBolle`.`ZipCodes` (`idZipCodes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`Users` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `tel` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `userID` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  `TypeUsers_idTypeUsers` INT NOT NULL,
  `Company_idCompany` INT NOT NULL,
  `RDV_idRDV` INT NOT NULL,
  `Factures_idFactures` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  `Address_ZipCodes_idZipCodes` INT NOT NULL,
  PRIMARY KEY (`idUsers`, `TypeUsers_idTypeUsers`, `Company_idCompany`, `RDV_idRDV`, `Factures_idFactures`, `Address_idAddress`, `Address_ZipCodes_idZipCodes`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC),
  INDEX `fk_Users_TypeUsers_idx` (`TypeUsers_idTypeUsers` ASC),
  INDEX `fk_Users_Company1_idx` (`Company_idCompany` ASC),
  INDEX `fk_Users_RDV1_idx` (`RDV_idRDV` ASC),
  INDEX `fk_Users_Factures1_idx` (`Factures_idFactures` ASC),
  INDEX `fk_Users_Address1_idx` (`Address_idAddress` ASC, `Address_ZipCodes_idZipCodes` ASC),
  CONSTRAINT `fk_Users_TypeUsers`
    FOREIGN KEY (`TypeUsers_idTypeUsers`)
    REFERENCES `immoOphelieBolle`.`TypeUsers` (`idTypeUsers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Users_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `immoOphelieBolle`.`Company` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Users_RDV1`
    FOREIGN KEY (`RDV_idRDV`)
    REFERENCES `immoOphelieBolle`.`RDV` (`idRDV`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Users_Factures1`
    FOREIGN KEY (`Factures_idFactures`)
    REFERENCES `immoOphelieBolle`.`Factures` (`idFactures`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Users_Address1`
    FOREIGN KEY (`Address_idAddress` , `Address_ZipCodes_idZipCodes`)
    REFERENCES `immoOphelieBolle`.`Address` (`idAddress` , `ZipCodes_idZipCodes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`TypeHouses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`TypeHouses` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`TypeHouses` (
  `idTypeHouses` INT NOT NULL AUTO_INCREMENT,
  `houseTypeName` VARCHAR(45) NULL,
  PRIMARY KEY (`idTypeHouses`),
  UNIQUE INDEX `idTypeHouses_UNIQUE` (`idTypeHouses` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`Statues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`Statues` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`Statues` (
  `idStatues` INT NOT NULL AUTO_INCREMENT,
  `statue` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatues`),
  UNIQUE INDEX `idStatues_UNIQUE` (`idStatues` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immoOphelieBolle`.`Houses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immoOphelieBolle`.`Houses` ;

CREATE TABLE IF NOT EXISTS `immoOphelieBolle`.`Houses` (
  `idHouses` INT NOT NULL AUTO_INCREMENT,
  `houseName` VARCHAR(45) NULL,
  `price` INT NULL,
  `roomNb` INT NULL,
  `bedroom` INT NULL,
  `bathroom` INT NULL,
  `surface` INT NULL,
  `vendu` TINYINT NULL,
  `garage` TINYINT NULL,
  `balcon` TINYINT NULL,
  `placard` TINYINT NULL,
  `pmr` TINYINT NULL,
  `parking` TINYINT NULL,
  `jardin` TINYINT NULL,
  `interphone` TINYINT NULL,
  `ascenceur` TINYINT NULL,
  `gardien` TINYINT NULL,
  `meubler` TINYINT NULL,
  `cheminee` TINYINT NULL,
  `colocation` TINYINT NULL,
  `TypeHouses_idTypeHouses` INT NOT NULL,
  `Statues_idStatues` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  `Address_ZipCodes_idZipCodes` INT NOT NULL,
  PRIMARY KEY (`idHouses`, `TypeHouses_idTypeHouses`, `Statues_idStatues`, `Address_idAddress`, `Address_ZipCodes_idZipCodes`),
  UNIQUE INDEX `idHouses_UNIQUE` (`idHouses` ASC),
  INDEX `fk_Houses_TypeHouses1_idx` (`TypeHouses_idTypeHouses` ASC),
  INDEX `fk_Houses_Statues1_idx` (`Statues_idStatues` ASC),
  INDEX `fk_Houses_Address1_idx` (`Address_idAddress` ASC, `Address_ZipCodes_idZipCodes` ASC),
  CONSTRAINT `fk_Houses_TypeHouses1`
    FOREIGN KEY (`TypeHouses_idTypeHouses`)
    REFERENCES `immoOphelieBolle`.`TypeHouses` (`idTypeHouses`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Houses_Statues1`
    FOREIGN KEY (`Statues_idStatues`)
    REFERENCES `immoOphelieBolle`.`Statues` (`idStatues`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Houses_Address1`
    FOREIGN KEY (`Address_idAddress` , `Address_ZipCodes_idZipCodes`)
    REFERENCES `immoOphelieBolle`.`Address` (`idAddress` , `ZipCodes_idZipCodes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
